# nixpacks.toml
[phases.install]
cmds = [
  "npm install --prefix backend",
  "cd backend && npx prisma generate",
  "npm install --prefix frontend" # Install frontend deps
]

[phases.build]
cmds = [
  "npm run build --prefix frontend" # Build frontend
]

# Start phase is handled by Procfile

# Optional: Explicitly define start phase if needed, though Procfile should still work
# [phases.start]
# cmd = "node backend/server.js" 